// Startbibliotek för nya konton (speglar frontendens src/lib/db/seed.ts).
export const SEED_ACTIVITIES: { title: string; frequency: "A" | "B" | "C" | "D" }[] = [
  { title: "Tända ljus", frequency: "A" },
  { title: "Ring någon", frequency: "A" },
  { title: "Rita en fågel", frequency: "A" },
  { title: "Läs minst 3 sidor", frequency: "A" },
  { title: "Rita något", frequency: "A" },
  { title: "Gör yoga (lite mjukt) på yogamatta", frequency: "A" },
  { title: "Skicka ett snällt meddelande till någon", frequency: "A" },

  { title: "Tänd rökelse", frequency: "B" },
  { title: "Bada i badkaret", frequency: "B" },
  { title: "Baka något", frequency: "B" },
  { title: "Måla något", frequency: "B" },
  { title: "Fixa naglar med fint lack", frequency: "B" },
  { title: "Gör mask för ansikte/fot/hand", frequency: "B" },
  { title: "Gör hårinpackning", frequency: "B" },
  { title: "Dansa", frequency: "B" },
  { title: "Boka in träff med någon för att göra något tillsammans", frequency: "B" },
  { title: "Laga något du aldrig lagat förr", frequency: "B" },

  { title: "Bjud in någon på middag", frequency: "C" },
  { title: "Boka in promenad i natur", frequency: "C" },
  { title: "Gå på promenad i naturen eller var i naturen", frequency: "C" },
  { title: "Åk till en brygga och sitt på den", frequency: "C" },
  { title: "Gör pyssel med pärlor", frequency: "C" },
  { title: "Pyssla med lera", frequency: "C" },
  { title: "Sticka något litet", frequency: "C" },
  { title: "Boka in bio", frequency: "C" },
  { title: "Boka in besök på museum med någon som sällskap", frequency: "C" },
  { title: "Boka något på salong", frequency: "C" },
  { title: "Boka resa till släkting", frequency: "C" },
  { title: "Boka in bowling/minigolf/shuffleboard", frequency: "C" },
  { title: "Planera in att bada", frequency: "C" },
  { title: "Sy något", frequency: "C" },
  { title: "Planera en liten utflykt", frequency: "C" },
  { title: "Boka en spontan mikrosemester", frequency: "C" },

  { title: "Boka in konsert/event", frequency: "D" },
  { title: "Boka in en kurs", frequency: "D" },
  { title: "Boka in brädspelskväll", frequency: "D" },
  { title: "Boka in fisketur", frequency: "D" },
];
